language: node_js # 指定语言环境
node_js:
  - "6" # 指定 NodeJS 版本1
dist: trusty # 指定系统版本。trusty 是指 Ubuntu 14.04 发行版的名称
sudo: required # 是否需要 sudo 权限

branches: # 指定要构建的分支
  only: # only 表示只构建以下分支
  - blog 


cache:
  directories:
    - node_modules
before_install:
  - git clone --branch master https://github.com/wushang1987/wushang1987.github.io public
  - npm install -g hexo
  - npm install -g hexo-cli
before_script:
  - git config --global user.name 'wushang1987'
  - git config --global user.email 'wushang1987@gmail.com'
  - sed -i'' "s~git@github.com:wushang1987/wushang1987.github.io.git~https://${ea37debcee6536f3a75601f8ff148271af4e3549}:x-oauth-basic@github.com/wushang1987/wushang1987.github.io.git~" _config.yml
install:
  - npm install
script:
  - npm run build
  - hexo clean
  - hexo generate
after_success:
  - cd public
  - git config user.name "wushang1987" 
  - git config user.email 'wushang1987@gmail.com'
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push https://$DEPLOY_TOKEN@github.com/wushang1987/wushang1987.github.io.git master

notifications: # 设置通知项
  email: true